### ISSUE TITLE
TypeError: Cannot read property 'getElementById' of undefined

### ISSUE THREAD

**Issue by jamescosford** [tues/binding.scala-deposit-calculator#1]
Thought you might be interested to know that I had an issue running this code sample today. I cloned the repo, checked out the first referenced commit in the tutorial (`72a46c13d9d2891604a9c8df88225184929b2c31`) and attempted to run it (`sbt run`)

Ended up with this exception:

```
[info] Loading global plugins from /[...]/.sbt/0.13/plugins
[info] Loading project definition from /[...]/learning/binding.scala-deposit-calculator/project
[info] Set current project to Binding.scala Deposit Calculator (in build file:/[...]/learning/binding.scala-deposit-calculator/)
[info] Compiling 1 Scala source to /[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/classes...
[info] Fast optimizing /[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/binding-scala-deposit-calculator-fastopt.js
[info] Running MainApp
[error] /[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/binding-scala-deposit-calculator-fastopt.js:4486
[error]   var parent = $m_Lorg_scalajs_dom_package$().document__Lorg_scalajs_dom_raw_HTMLDocument().getElementById("mainContainer");
[error]                                                                                            ^
[error] 
[error] TypeError: Cannot read property 'getElementById' of undefined
[error]     at $c_LMainApp$.main__V (/[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/binding-scala-deposit-calculator-fastopt.js:4486:92)
[error]     at Object.<anonymous> (/[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/binding-scala-deposit-calculator-fastopt.js:23966:16)
[error]     at Object.<anonymous> (/[...]/learning/binding.scala-deposit-calculator/target/scala-2.11/binding-scala-deposit-calculator-fastopt.js:23967:4)
[error]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[error]     at Module.load (internal/modules/cjs/loader.js:599:32)
[error]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[error]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[error]     at Module.require (internal/modules/cjs/loader.js:637:17)
[error]     at require (internal/modules/cjs/helpers.js:20:18)
org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
    at org.scalajs.jsenv.ExternalJSEnv$AbstractExtRunner.waitForVM(ExternalJSEnv.scala:119)
    at org.scalajs.jsenv.ExternalJSEnv$ExtRunner.run(ExternalJSEnv.scala:168)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$.org$scalajs$sbtplugin$ScalaJSPluginInternal$$jsRun(ScalaJSPluginInternal.scala:701)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$73$$anonfun$apply$48$$anonfun$apply$49.apply(ScalaJSPluginInternal.scala:818)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$73$$anonfun$apply$48$$anonfun$apply$49.apply(ScalaJSPluginInternal.scala:812)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) org.scalajs.jsenv.ExternalJSEnv$NonZeroExitException: Node.js exited with code 1
[error] Total time: 15 s, completed 13/11/2018 9:07:41 PM
```

I appreciate the tutorial, and still got a lot of value out of it, but I would have really liked it if it had worked :P any ideas?

**Comment by jamescosford** [comment]
Had the same issue when I attempted to run master too*

**Comment by jamescosford** [comment]
I think this was just down to me being an idiot. Sorry for the false alarm.
